sudo: false
language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
    - "nightly"
env:
  - DJANGO=1.8
  - DJANGO=1.11
  - DJANGO=2.2
  - DJANGO=3.0
  - DJANGO=dev

matrix:
  fast_finish: true
  include:
    - env: TOXENV=qa
      python: "3.7"
    - env: TOXENV=py37-django-dev
      python: "3.7"
  exclude:
    # Python/Django combinations that aren't officially supported
    - { env: DJANGO=1.11, python: "3.7" }
    - { env: DJANGO=1.11, python: "3.8" }
    - { env: DJANGO=3.0, python: "3.5" }
  allow_failures:
    - env: DJANGO=1.8
    - env: DJANGO=1.11


install: pip install tox-travis python-coveralls codecov

script: tox
after_success:
  - codecov
